######################
# Generate True Data #
######################

#' Title
#'
#' @param n
#' @param model
#' @param p
#' @param bb0
#' @param bb
#' @param x.sd
#' @param v1
#' @param v2
#' @param dist
#' @param eps.sd
#' @param u.sd
#'
#' @return a data frame for a simulated longitudinal data containing subject ID, subject specific covariates,
#'         true  inflection points, longitudinal time points, longitudinal response and gender.
#' @export
#'
#' @examples mydata(n=80, model="logist", p=2, bb0=0.5, bb=0.1, x.sd=0.3, v1=5, v2=7, dist="normal", eps.sd=0.05, u.sd=0.05)
#'
#'
#'
mydata<-function(n=80, model="logist",  p=2, bb0=1, bb=1, x.sd=5, v1=5, v2=7, dist="normal", eps.sd=0.05, u.sd=0.05){



  #################################################################################
  ## gender is created: 30% for male and 70% for females based on the real data ###
  #################################################################################

  gender<-sample(c("Male", "Female"), size=n, replace=TRUE, prob=c(0.3,0.7))


  ########################################
  ## generate data for each subject i   ##
  ########################################

  ## list format of observed HD data
  datgen<-vector("list", n)

  ## vector of visit numbers: different for different patients; 30% for 5 visits, 60% for 6 visits, 10% for 7 visits
  visit.num<-sample(v1:v2, n, replace=TRUE, prob=c(0.3, 0.6, 0.1))


  raw.tms.data<-array(0, dim=c(sum(visit.num),7),
                      dimnames=list(paste("xx", 1:sum(visit.num), sep=""),c("subj.id", "subj.cov", "true_logt", "ages", "omega", "tms", "sex")
                      ))




  for (id in 1:n){

    ## vector of subject ID ###

    subj.visit.number<-visit.num[id]
    subj.id<-rep(id, subj.visit.number)


    ## vector of gender  ###

    gender_level<-ifelse(gender[id]=="Male",1,0)
    sex<-rep(gender_level,visit.num[id])


    ###########################################
    ## Model for log of Inflection point T  ###
    ###########################################

    ## covariate W is uniform random number on (2,3)
    #p<-2
    ww<-runif(p-1,35, 50)


    ## error terms
    if (dist=="normal"){
      ee<-rnorm(1,0,u.sd)
    }



    beta<-c(bb0,bb)   ##  input for beta components
    W<-c(1,ww)        ##  ww is true covariate assocaited with log inflection point

    ################################################
    ## estimate log of inflection points         ###
    ################################################
    betaW<-crossprod(beta,W)   #t(as.vector(beta))%*%(as.vector(W));
    true_z<-betaW+ee;


    ## true inflection points should be in the range of logage
    xx<-sort(rnorm(visit.num[id],true_z,x.sd))


    ## error term for longitudinal model,
    ##            which follows normal distribution with mean 0 and standard deviation sigma

    if (dist=="normal"){
      eps.star<-rnorm(visit.num[id],0, eps.sd)
    }

    ## function omega generated by function w()
    true_z<-as.numeric(true_z)
    omega<-w(xx,true_z, model)

    ## longitudinal response: total motor score y
    yy<-omega+eps.star

    ## add covariate values
    cov.W<-rep(ww, visit.num[id])

    datgen[[id]]<-cbind(subj.id, cov.W, true_z, xx, omega, yy, sex)


  }




  ## create data.frame from list type of data
  gendat<-do.call("rbind.data.frame", datgen)
  raw.tms.data<-gendat

  return(raw.tms.data)

}
